### PR TITLE
Add advanced database schema exercise for lesson 3

### PR DESCRIPTION
**Pull request by flemeur**

### CODE REVIEW

**Review by martamatos — COMMENTED** [review]
The social media DB exercise looks good. 
Is it instead of the book/author database schema they used to do?
Is it not too hard for them?

**Comment by flemeur** [comment]
> Is it instead of the book/author database schema they used to do?

It was just something I used last time to have an exercise in the final lesson. Benjamin suggested that I should add it to the repo. So not really a replacement for the other exercises.

> Is it not too hard for them?

It's definitely tricky, but my thoughts were that it would get the students to think more about the different relations involved and discus the pros and cons of different solutions.

**Comment by martamatos** [comment]
If it's an extra exercise then i think it's great :D. I was only concerned if it would substitute the previous one with the book/author database :)

**Comment by flemeur** [comment]
Perfect! I'll go ahead and merge it then :)

**Pull request merged**
